# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.8.3

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.podman.annotations.userns/mqttserver: keep-id
  labels:
    app: mqttserver-pod
  name: mqttserver-pod
spec:
  containers:
  - args:
    - /usr/sbin/mosquitto
    - -c
    - /mosquitto/config/mosquitto.conf
    env:
    - name: TERM
      value: xterm
    image: docker.io/library/eclipse-mosquitto:latest
    name: mqttserver
    ports:
    - containerPort: 1883
      hostPort: 1883
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /mosquitto/log
      name: mosquitto-log-host-0
    - mountPath: /mosquitto/data
      name: mosquitto-data-host-1
    - mountPath: /mosquitto/config
      name: mosquitto-config-host-2
  hostUsers: false
  volumes:
  - hostPath:
      path: ./mosquitto/log
      type: Directory
    name: mosquitto-log-host-0
  - hostPath:
      path: ./mosquitto/data
      type: Directory
    name: mosquitto-data-host-1
  - hostPath:
      path: ./mosquitto/config
      type: Directory
    name: mosquitto-config-host-2

